### PR TITLE
Fixed new nette/forms rendering

### LINKED ISSUE #219: New nette/forms brokem forms visitor
Generated code to get form field now looks like this:

```php
\Nette\Bridges\FormsLatte\Runtime::item('select', $this->global)
```

it does same thing as previous version

```php
$this->global->formsStack['select'];
```

We need to replace both versions with analysable reference to `$form`

### PR DESCRIPTION
**Pull request by lulco**
Resolves https://github.com/efabrica-team/phpstan-latte/issues/219

### CODE REVIEW

File: src/Compiler/NodeVisitor/AddFormClassesNodeVisitor.php [hunk 1]
```diff
@@ -167,11 +197,36 @@ public function leaveNode(Node $node)
         ) {
             $varName = $this->nameResolver->resolve($node->expr->var);
             if ($varName === 'ʟ_input' || $varName === '_input') {
-                $node->setDocComment(new Doc('/** @var Nette\Forms\Controls\BaseControl ' . $varName . ' @phpstan-ignore-next-line */'));
+                $node->setDocComment(new Doc('/** @var Nette\Forms\Controls\BaseControl $' . $varName . ' @phpstan-ignore-next-line */'));
                 return $node;
             }
         }
 
+        if ($node instanceof Echo_ && ($node->exprs[0] ?? null) instanceof MethodCall) {
```
Comment (MartinMystikJonas) [inline src/Compiler/NodeVisitor/AddFormClassesNodeVisitor.php:232]: Maybe add comment about what is replaced with what here

File: src/Compiler/NodeVisitor/AddFormClassesNodeVisitor.php [hunk 2]
```diff
@@ -101,10 +103,38 @@ public function enterNode(Node $node): ?Node
             $this->actualForm = $this->forms[$formName] ?? null;
             return new Assign(new Variable('form'), new New_(new Name($formClassName)));
         } elseif ($node instanceof StaticCall) {
-            if ($this->nameResolver->resolve($node) === 'renderFormEnd') {
-                $node->args[0] = new Arg(new Variable('form'));
-                $this->actualForm = null;
-                return $node;
+            if ($this->nameResolver->resolve($node->class) === 'Nette\Bridges\FormsLatte\Runtime') {
```
Comment (MartinMystikJonas) [inline src/Compiler/NodeVisitor/AddFormClassesNodeVisitor.php:106]: Here too.

**Review by MartinMystikJonas — APPROVED** [review]
