### PR TITLE
Line of compilation error (if available) instead of -1

### LINKED ISSUE #356: Try to handle error line for compilation errors
Now, if there is some exception, we use line -1. Check if there is any chance to identify real latte line

### PR DESCRIPTION
**Pull request by lulco**
Resolves https://github.com/efabrica-team/phpstan-latte/issues/356

### CODE REVIEW

File: src/Compiler/Compiler/Latte2Compiler.php [hunk 1]
```diff
@@ -43,16 +44,27 @@ protected function createDefaultEngine(): Engine
...
+            $phpContent = $compiler
+                ->setFunctions(array_keys($this->getDefaultFunctions()))
+                ->compile(
+                    $latteTokens,
+                    $className,
+                    $this->generateClassComment($className, $context),
+                    $this->strictMode
+                );
+        } catch (CompileException $e) {
+            $line = isset($latteTokens)
```
Comment (lulco) [inline src/Compiler/Compiler/Latte2Compiler.php:61]: inspired by latte 2 Engine

File: tests/Rule/LatteTemplatesRule/PresenterWithoutModule/LatteTemplatesRuleForPresenterTest.php [hunk 2]
```diff
@@ -825,6 +826,11 @@ public function testStartupView(): void
     public function testSnippets(): void
     {
         $this->analyse([__DIR__ . '/Fixtures/SnippetsPresenter.php'], [
+            [
+                'Combination of n:snippet with n:foreach is invalid, use n:inner-foreach ' . (LatteVersion::isLatte3() ? '(on line 3 at column 6)' : '(on line 3)'),
```
Comment (lulco) [inline tests/Rule/LatteTemplatesRule/PresenterWithoutModule/LatteTemplatesRuleForPresenterTest.php:830]: messages are different in latte 2 and latte 3, but I think it is good to know here the error raised so I keep it there.

**Review by MartinMystikJonas — APPROVED** [review]
