### PR TITLE
Variable subcollectors + support for assign to array / list of template variables

### LINKED ISSUE #200: Assign to array of template variables not work
```
[$this->template->foo, $this->template->bar] = $someArrayOrFunctionOrMethodCall;
```

### PR DESCRIPTION
**Pull request by lulco**
Resolves https://github.com/efabrica-team/phpstan-latte/issues/200

### CODE REVIEW

File: src/LatteContext/Collector/VariableCollector/AssignToTemplateVariableCollector.php [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+        }
+
+        if (!$this->isTemplateType($node->var, $scope)) {
+            return [];
+        }
+
+        $variableType = $this->typeResolver->resolveAsConstantType($node->expr, $scope);
+        if ($variableType === null) {
+            $variableType = $scope->getType($node->expr);
+        }
```
Comment (MartinMystikJonas) [inline src/LatteContext/Collector/VariableCollector/AssignToTemplateVariableCollector.php:43]: There should be phpdoc handling but I can add it later (just create issue for me pls)

**Comment by MartinMystikJonas** [comment]
I am still nmto sure about two-level structure but we might need some common logic lates so I think we can keep it this way

**Review by MartinMystikJonas — APPROVED** [review]

File: src/LatteContext/Collector/VariableCollector/AssignToTemplateVariableCollector.php (hunk 1 above)
Comment (lulco) [reply src/LatteContext/Collector/VariableCollector/AssignToTemplateVariableCollector.php:43]: phpdoc handling is in AbstractAssignVariableCollector
[here](https://github.com/efabrica-team/phpstan-latte/pull/205/files#diff-15d17f9cc7efa663cc2b5cc5899b6a88d80fabafbcb7a42b2161026a9618def0R46) and [here](https://github.com/efabrica-team/phpstan-latte/pull/205/files#diff-15d17f9cc7efa663cc2b5cc5899b6a88d80fabafbcb7a42b2161026a9618def0R57)

but there should be some phpdoc handling for array assign
