### PR TITLE
Fixed dynamic labels in form templates

### LINKED ISSUE #352: Call to an undefined method Nette\Forms\Control::getLabel().
I started getting these errors after composer update on one of our projects where we use form templates.

```
Call to an undefined method Nette\Forms\Control::getLabel().
```

for dynamic labels:

```latte
{label $name /}
```

Compiled template looks like this:

```php
echo $ʟ_label = \Nette\Bridges\FormsLatte\Runtime::item($name, $this->global)->getLabel();
```

Any idea why this did not showed earlier? Is it something we changed our side or some change in latte?

### PR DESCRIPTION
**Pull request by MartinMystikJonas**
Resolves #352

### CODE REVIEW

File: src/Compiler/NodeVisitor/AddFormClassesNodeVisitor.php [hunk 1]
```diff
@@ -266,6 +266,7 @@ public function leaveNode(Node $node)
          * </code>
          */
         if ($node instanceof Echo_ && ($node->exprs[0] ?? null) instanceof MethodCall) {
+            $varName = 'ʟ_input';
```
Comment (MartinMystikJonas) [inline src/Compiler/NodeVisitor/AddFormClassesNodeVisitor.php:269]: Moved to same place to keep it similar to following code

File: tests/Rule/LatteTemplatesRule/PresenterWithoutModule/Fixtures/templates/Forms/default.latte [hunk 2]
```diff
@@ -1,7 +1,7 @@
 {form firstForm}
     {input text} <label n:name="text">Text</label><input n:name="text">
     {input textarea id => "myId"}
-    {input password}
+    {input password}{label password /}
```
Comment (lulco) [inline tests/Rule/LatteTemplatesRule/PresenterWithoutModule/Fixtures/templates/Forms/default.latte]: I think we have covered this, see line 12, 15 etc

**Review by lulco — APPROVED** [review]
