### PR TITLE
Fixed error when analysing classes using self:: or static:: in method calls

### LINKED ISSUE #145: Class self was not found while trying to analyse it - discovering symbols is probably not configured properly.
We got this error in real app when extension is active. It is not caused by rule becaus eerror occurs even without it. My guess it is somewhere in collectors but I need to investigate.

### PR DESCRIPTION
**Pull request by MartinMystikJonas**
Resolves #145

### CODE REVIEW

**Review by lulco — APPROVED** [review]

File: src/Resolver/CallResolver/CalledClassResolver.php [hunk 1]
```diff
@@ -37,6 +37,8 @@ public function resolve(Node $node, Scope $scope): ?string
                     return null;
                 }
                 return $classReflection->getName();
+            } elseif($calledClassName === 'self' || $calledClassName === 'static')  {
```
Comment (lulco) [inline src/Resolver/CallResolver/CalledClassResolver.php]: one space is missing here, but Checks don't run now, I don't know why

**Comment by lulco** [comment]
This is approved
